### ISSUE TITLE
Fluent With Photino

### ISSUE THREAD

**Issue by ortega-01** [tryphotino/photino.Blazor#132]
When trying to add fluent to photino blazor, I get this error whenever I refresh the page:

JS object instance with ID 1 does not exist (has it been disposed?).
Error: JS object instance with ID 1 does not exist (has it been disposed?).
    at w (http://localhost/_framework/blazor.webview.js:1:5273)
    at http://localhost/_framework/blazor.webview.js:1:3044
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (http://localhost/_framework/blazor.webview.js:1:3007)
    at http://localhost/_framework/blazor.webview.js:1:48308
    at EventTarget.<anonymous> (<anonymous>:1:202)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:43835)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode.DisposeAsync() in C:\Users\Danny\source\repos\fluentui-blazor\src\Core\Components\KeyCode\FluentKeyCode.razor.cs:line 183
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()

Here is my program.cs:

`internal class Program
{
    [STAThread]
    static void Main(string[] args)
    {
        var appBuilder = PhotinoBlazorAppBuilder.CreateDefault(args);

        appBuilder.Services
            .AddLogging();

        appBuilder.Services.AddFluentUIComponents();

        // register root component and selector
        appBuilder.RootComponents.Add<PhotinoApp>("app");

        var app = appBuilder.Build();

        // customize window
        app.MainWindow
            .SetIconFile("favicon.ico")
            .SetTitle("ECM Control Panel");

        AppDomain.CurrentDomain.UnhandledException += (sender, error) =>
        {
            app.MainWindow.ShowMessage("Fatal exception", error.ExceptionObject.ToString());
        };

        app.Run();
    }
}`

Possible Problem:
I'm unable to call:
 `// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();`

**Comment by jurica** [comment]
Hi @ortega-01,
do you still have problems get Fluent UI to work in your Photino app?
I just figured it out and it works for me in my project.
You can find it here: https://github.com/jurica/Zuschnitt/tree/main/Zuschnitt.Blazor.Photino
Hope it helps...

**Comment by MikeYeager** [comment]
Please re-open if the solution does not work for you.
